
GET http://localhost:3000/api/employee 

###
POST http://localhost:3000/api/employee
Content-Type: application/json

{
    "name": "talia", 
    "last_name": "alcivar",
    "email": "talcivat@gmail.com", 
    "dni": "12345678",
    "cell_phone": "098765432"
}


###
PUT http://localhost:3000/api/employee/2
Content-Type: application/json

{
    "name": "thalia", 
    "last_name": "alcivar",
    "email": "talcivat@gmail.com", 
    "dni": "12345678",
    "cell_phone": "098765432"
}

###
DELETE http://localhost:3000/api/employee/2




