GET http://localhost:3000/api/materials

###
POST http://localhost:3000/api/materials
Content-Type: application/json

{
    "name": "Cemento", 
    "price": 25.00, 
    "sku": "MP-0000001", 
    "material_type_id": 1
}

###
PUT http://localhost:3000/api/materials/1
Content-Type: application/json

{
    "name": "Martillo", 
    "price": 4.50, 
    "sku": "PT-0000001", 
    "material_type_id": 3
}