GET http://localhost:3000/api/materials-locations

###
GET http://localhost:3000/api/materials-locations/warehouses/1?locationId=1

###
POST http://localhost:3000/api/materials-locations
Content-Type: application/json

{
    "material_id": 11,
    "location_id": 6,
    "stock": 125
}