GET http://localhost:3000/api/materials-locations/1

###
GET http://localhost:3000/api/materials-locations/2/locations/6

###
POST http://localhost:3000/api/materials-locations
Content-Type: application/json

{
    "materialId": 11,
    "locationId": 1,
    "stock": 325
}