GET http://localhost:3000/api/orders

###
GET http://localhost:3000/api/orders/5

###
POST http://localhost:3000/api/orders
Content-Type: application/json

{
    "out_date": "2022-09-20", 
    "truck_plate": "ABG-780", 
    "stateId": 1, 
    "originId": 2, 
    "destinyId": 3
}

###
PUT http://localhost:3000/api/orders/5
Content-Type: application/json

{
    "out_date": "2022-09-26", 
    "truck_plate": "ABG-980", 
    "stateId": 2, 
    "originId": 2, 
    "destinyId": 3
}

###
DELETE http://localhost:3000/api/orders/1