GET http://localhost:3000/api/orders
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNSwidXNlcl9yb2xlIjoiT3BlcmFyaW8iLCJleHBpcmF0aW9uX2RhdGUiOjE2NzAxMDQ3OTMsImlhdCI6MTY3MDEwNDQ5M30.RMlCKyyJ4kuFNn-pphrSiLC_cNZb1CY4p2S_UMKujvw

###
GET http://localhost:3000/api/orders/5

###
POST http://localhost:3000/api/orders
Content-Type: application/json

{
    "out_date": "2022-09-20", 
    "truck_plate": "ABG-780", 
    "stateId": 1, 
    "originId": 2, 
    "destinyId": 3
}

###
PUT http://localhost:3000/api/orders/5
Content-Type: application/json

{
    "out_date": "2022-09-26", 
    "truck_plate": "ABG-980", 
    "stateId": 2, 
    "originId": 2, 
    "destinyId": 3
}

###
PATCH  http://localhost:3000/api/orders/12
Content-Type: application/json

{
    "stateId": 4
}

###
DELETE http://localhost:3000/api/orders/6